# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

vars:
  SLIM_BINDINGS_VERSION: '{{.SLIM_BINDINGS_VERSION | default "0.7.3"}}'
  SLIM_DIR: '{{.SLIM_DIR | default "../slim"}}'
  UNIFFI_BINDGEN_CS_VERSION: "v0.9.0+v0.28.3"
  CONFIG: '{{.CONFIG | default "Release"}}'

tasks:
  default:
    cmds:
      - task -l

  setup:
    desc: Download pre-built native libraries for local development
    cmds:
      - task: download

  download:
    desc: Download pre-built native libraries from slim release
    cmds:
      - mkdir -p artifacts
      - gh release download slim-bindings-libs-v{{.SLIM_BINDINGS_VERSION}} --repo agntcy/slim --pattern "*.zip" --dir artifacts/ --clobber
      - |
        for zip in artifacts/*.zip; do
          target="${zip#artifacts/slim-bindings-}"
          target="${target%.zip}"
          case "$target" in
            x86_64-unknown-linux-gnu)   rid="linux-x64" ;;
            aarch64-unknown-linux-gnu)  rid="linux-arm64" ;;
            x86_64-apple-darwin)        rid="osx-x64" ;;
            aarch64-apple-darwin)       rid="osx-arm64" ;;
            x86_64-pc-windows-msvc)     rid="win-x64" ;;
            *) continue ;;
          esac
          mkdir -p "runtimes/$rid/native"
          unzip -oj "$zip" -d "runtimes/$rid/native/"
        done
        rm -rf artifacts
        find runtimes -type f ! \( -name "*.so" -o -name "*.dylib" -o -name "*.dll" \) -delete
        for dir in runtimes/*/native; do
          for f in "$dir"/*slim_bindings*; do
            [ -f "$f" ] || continue
            case "$f" in
              *.so)    mv "$f" "$dir/libslim_bindings.so" ;;
              *.dylib) mv "$f" "$dir/libslim_bindings.dylib" ;;
              *.dll)   mv "$f" "$dir/slim_bindings.dll" ;;
            esac
          done
        done

  regenerate:
    desc: Regenerate C# bindings (requires slim repo at ../slim)
    cmds:
      - |
        if [ ! -d "{{.SLIM_DIR}}/data-plane/bindings/rust" ]; then
          echo "Error: slim repo not found at {{.SLIM_DIR}}" >&2
          echo "Clone it: git clone https://github.com/agntcy/slim.git {{.SLIM_DIR}}" >&2
          exit 1
        fi
      - task: download
      - cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs.git --tag {{.UNIFFI_BINDGEN_CS_VERSION}} 2>/dev/null || true
      - mkdir -p Slim/generated
      - |
        if [ -f "runtimes/osx-arm64/native/libslim_bindings.dylib" ]; then
          lib="$(pwd)/runtimes/osx-arm64/native/libslim_bindings.dylib"
        elif [ -f "runtimes/osx-x64/native/libslim_bindings.dylib" ]; then
          lib="$(pwd)/runtimes/osx-x64/native/libslim_bindings.dylib"
        else
          lib="$(pwd)/runtimes/linux-x64/native/libslim_bindings.so"
        fi
        cd {{.SLIM_DIR}}/data-plane/bindings/rust
        uniffi-bindgen-cs --library "$lib" --out-dir "$OLDPWD/Slim/generated"

  build:
    desc: Build the C# project
    cmds:
      - dotnet build Slim.sln -c {{.CONFIG}}

  test:
    desc: Run all tests
    cmds:
      - dotnet test Slim.sln -c {{.CONFIG}} {{.CLI_ARGS}}

  test:smoke:
    desc: Run smoke tests (no server required)
    cmds:
      - dotnet test Slim.sln -c {{.CONFIG}} --filter "Category!=Integration" {{.CLI_ARGS}}

  test:ci:
    desc: Run smoke tests in CI (copies native lib to output)
    cmds:
      - task: build
      - cp runtimes/linux-x64/native/libslim_bindings.so Slim.Tests/bin/{{.CONFIG}}/net8.0/
      - dotnet test Slim.sln -c {{.CONFIG}} --filter "Category!=Integration" --no-build

  pack:
    desc: Create NuGet package
    cmds:
      - dotnet pack Slim/Slim.csproj -c Release -o packages/

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf runtimes packages artifacts
      - dotnet clean Slim.sln 2>/dev/null || true
