# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: "3"

vars:
  SLIM_BINDINGS_VERSION: '{{.SLIM_BINDINGS_VERSION | default "0.7.3"}}'
  UNIFFI_BINDGEN_CS_VERSION: "v0.9.0+v0.28.3"

tasks:
  default:
    cmds:
      - task -l

  setup:
    desc: Download pre-built libraries and generate C# bindings
    cmds:
      - task: download
      - task: generate-bindings

  download:
    desc: Download pre-built native libraries from slim release
    cmds:
      - mkdir -p artifacts
      - gh release download slim-bindings-libs-v{{.SLIM_BINDINGS_VERSION}} --repo agntcy/slim --pattern "*.zip" --dir artifacts/ --clobber
      - |
        for zip in artifacts/*.zip; do
          target="${zip#artifacts/slim-bindings-}"
          target="${target%.zip}"
          case "$target" in
            x86_64-unknown-linux-gnu)   rid="linux-x64" ;;
            x86_64-unknown-linux-musl)  rid="linux-musl-x64" ;;
            aarch64-unknown-linux-gnu)  rid="linux-arm64" ;;
            aarch64-unknown-linux-musl) rid="linux-musl-arm64" ;;
            x86_64-apple-darwin)        rid="osx-x64" ;;
            aarch64-apple-darwin)       rid="osx-arm64" ;;
            x86_64-pc-windows-msvc)     rid="win-x64" ;;
            x86_64-pc-windows-gnu)      rid="win-x64-gnu" ;;
            *) continue ;;
          esac
          mkdir -p "runtimes/$rid/native"
          unzip -oj "$zip" -d "runtimes/$rid/native/"
          for f in runtimes/$rid/native/*slim_bindings*; do
            case "$f" in
              *.so)    mv "$f" "runtimes/$rid/native/libslim_bindings.so" ;;
              *.dylib) mv "$f" "runtimes/$rid/native/libslim_bindings.dylib" ;;
              *.dll)   mv "$f" "runtimes/$rid/native/slim_bindings.dll" ;;
            esac
          done
        done
        rm -rf artifacts
      - echo "Libraries downloaded to runtimes/"

  generate-bindings:
    desc: Generate C# bindings from native library
    cmds:
      - cargo install uniffi-bindgen-cs --git https://github.com/NordSecurity/uniffi-bindgen-cs.git --tag {{.UNIFFI_BINDGEN_CS_VERSION}} 2>/dev/null || true
      - mkdir -p SlimBindings/generated
      - |
        if [ -f "runtimes/osx-arm64/native/libslim_bindings.dylib" ]; then
          lib="runtimes/osx-arm64/native/libslim_bindings.dylib"
        elif [ -f "runtimes/osx-x64/native/libslim_bindings.dylib" ]; then
          lib="runtimes/osx-x64/native/libslim_bindings.dylib"
        elif [ -f "runtimes/linux-x64/native/libslim_bindings.so" ]; then
          lib="runtimes/linux-x64/native/libslim_bindings.so"
        else
          echo "No native library found. Run 'task download' first." >&2
          exit 1
        fi
        uniffi-bindgen-cs --library "$lib" --out-dir SlimBindings/generated
      - echo "Bindings generated in SlimBindings/generated/"

  build:
    desc: Build the C# project
    cmds:
      - dotnet build SlimBindings.sln

  test:
    desc: Run tests
    cmds:
      - dotnet test SlimBindings.sln {{.CLI_ARGS}}

  test:smoke:
    desc: Run smoke tests (no server required)
    cmds:
      - dotnet test SlimBindings.sln --filter "Category!=Integration" {{.CLI_ARGS}}

  pack:
    desc: Create NuGet package
    cmds:
      - dotnet pack SlimBindings/SlimBindings.csproj -c Release -o packages/

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf SlimBindings/generated runtimes packages artifacts
      - dotnet clean SlimBindings.sln 2>/dev/null || true
